name: Continuous Integration

on: push

env:
  BITBUCKET_TEST_USERNAME:  ${{ secrets.BITBUCKET_TEST_USERNAME }}
  BITBUCKET_TEST_PASSWORD:  ${{ secrets.BITBUCKET_TEST_PASSWORD }}
  BITBUCKET_TEST_OWNER:  ${{ secrets.BITBUCKET_TEST_OWNER }}
  BITBUCKET_TEST_REPOSLUG:  ${{ secrets.BITBUCKET_TEST_REPOSLUG }}

jobs:
  all-tests:
    name: All Tests
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false # When all tests are consistently passing this should be turned off
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
        go: [1.12, 1.13, 1.14, 1.15]
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Setup Go ${{ matrix.go }}
        uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go }}
      - name: Run tests
        run: make test

  # This job is intended to only exist temporarily.
  # To give greater visibility on which files are failing,
  # while the errors with the tests are resolved
  individual-tests:
    name: Run ${{ matrix.file }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false # When all tests are consistently passing this should be turned off
      matrix:
        os: [ macos-latest, windows-latest, ubuntu-latest ]
        go: [ 1.12, 1.13, 1.14, 1.15 ]
        file:
          - branchrestrictions_test.go
          - client_test.go
          - diff_test.go
          - list_test.go
          - repository_test.go
          - user_test.go
          - workspace_test.go
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Setup Go ${{ matrix.go }}
        uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go }}
      - name: Run ${{ matrix.file }}
        run: go test -v ./tests/${{ matrix.file }}
